# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-03 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('marks', models.FloatField()),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobno', models.IntegerField()),
            ],
        ),
    ]
